### ISSUE TITLE
_key.currentState.toggle() is not working

### ISSUE THREAD

**Issue by Shiba-Kar** [NikhilVadoliya/Flutter_slider_drawer#1]

**Comment by nikhil-concetto** [comment]
Thanks Shiba-Kar, I will check it and fix into new update.Meanwhile you should be use `closeDrawer`,`openDrawer` and `isDrawerOpen` method.

**Comment by nikhil-concetto** [comment]
Hi Shiba-Kar, I have solved this issue. Please update plugin.

**Comment by NikhilVadoliya** [comment]
Now, `toggle` method working fine so close it.
