### ISSUE TITLE
In windows if the drawer has enough space in the window it should show initially expanded

### ISSUE THREAD

**Issue by Josua2012** [NikhilVadoliya/Flutter_slider_drawer#12]
Hi,
In windows (desktop) if the drawer has enough space in the window it should show initially expanded.
Thanks a lot. 
Regards,
Jose.

**Comment by NikhilVadoliya** [comment]
No it will not expaned if have enough space in web/window platform.
If you want it then temporary call  `_key.currentState.openDrawer()` method after build complete.

**Comment by mrnotepad** [comment]
i tried to put _sliderDrawerKey.currentState!.openSlider(); to init state but not working
