### ISSUE TITLE
_key.currentState is always null

### ISSUE THREAD

**Issue by thenixoncompany** [NikhilVadoliya/Flutter_slider_drawer#14]
_key.currentState is always null and it's not possible to use the drawer operations.
How it's possible to solve it?

**Comment by NikhilVadoliya** [comment]
Did you set key with `SliderMenuContainer` widget ?

For Example 

 ```
SliderMenuContainer(
        appBarColor: Colors.white,
        key: _key,
        sliderMenuOpenSize: 200,
        title: Text(.....
```

**Comment by thenixoncompany** [comment]
sorry, my mistake. 
you made me realize that it was to be set for `SliderMenuContainer`.
I incorrectly set it for `Scaffold`. 

thank you very much
