### ISSUE TITLE
How to add Custoem AppBar with menus

### ISSUE THREAD

**Issue by JagadishaIncture** [NikhilVadoliya/Flutter_slider_drawer#18]
I need to add AppBar with action menus how to add?

**Comment by NikhilVadoliya** [comment]
Hello @JagadishaIncture , Can you please share you wire-frame of your UI?

**Comment by NikhilVadoliya** [comment]
Hello @JagadishaIncture , Please update plugin with version 2.1.1. You can use custom app bar in latest version of plugin.

**Comment by JagadishaIncture** [comment]
Sure Thanks
