### ISSUE TITLE
closeDrawer() programmatically not set isDrawerOpen to false.

### ISSUE THREAD

**Issue by hoppham2332** [NikhilVadoliya/Flutter_slider_drawer#2]
I tried to close drawer when user tap outside the menu ( tap on MainWidget) by closeDrawer(), it closed the menu but the var isDrawerOpen still have value is true. I think it must be set to false whenever menu is closed?

```
flutter_slider_drawer: ^1.0.1
Flutter 1.20.0-8.0.pre.40 • channel unknown • unknown source
Framework • revision 6eaaf1650e (27 hours ago) • 2020-07-09 18:04:37 -0700
Engine • revision 9b3e3410f0
Tools • Dart 2.9.0 (build 2.9.0-20.0.dev 06cb010247)

```

**Comment by NikhilVadoliya** [comment]
It's always updating value of `isDrawerOpen` whenever `closeDrawer()/openDrawer()/toggle()` method called. 

- `isDrawerOpen` = false  when `closeDrawer() `
- `isDrawerOpen` = true  when  `openDrawer()`

Please share you code or update plugin.

**Comment by hoppham2332** [comment]
@NikhilVadoliya  Here is my code when user tap to MainWidget:
debugPrint isDrawerOpen = false only when I close the menu by 'X' button.

`void _pressed() {
    
    if (_keyMenu.currentState.isDrawerOpen) {
      _keyMenu.currentState.closeDrawer();
    } else {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => detailPage),
      );
    }
    debugPrint("state: " + _keyMenu.currentState.isDrawerOpen.toString());
  }`


Here is code define slider

` 
home: Scaffold(
          body: SliderMenuContainer(
              appBarColor: Colors.white,
              key: _keyMenu,
              appBarPadding: const EdgeInsets.only(top: 20),
              sliderMenuOpenOffset: 200,
              appBarHeight: 60,
              title: Text(
                title,
                style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
              ),
              sliderMenuWidget: MenuWidget(
                onItemClick: (category) {
                  _keyMenu.currentState.closeDrawer();
                  setState(() {
                    this.title = category.name;
                    fetchAnimes(category);
                  });
                },
              ),
              sliderMainWidget: homeSection))
`
