### ISSUE TITLE
useless documentation 

### ISSUE THREAD

**Issue by hixcoder** [NikhilVadoliya/Flutter_slider_drawer#20]
Hello Dorin ,
I like the drawer you did, but it is hard to use it with the documentation provided in the pub.dev site,
so please if you have some time , can you make a more explained docs for this awesome package.
thanks bro!

**Comment by NikhilVadoliya** [comment]
Okay @hixcoder , I will improve documentation in this plugin. Thanks for feedback

**Comment by NikhilVadoliya** [comment]
Hello @hixcoder, I have updated documentation in version 2.1.0.
