### ISSUE TITLE
[BUG] direction is right, can't current work on style1

### ISSUE THREAD

**Issue by wuribatu** [NikhilVadoliya/Flutter_slider_drawer#25]
when isRtl: true, style: DrawerStyle.style1, menuScreen at incurrent location.
ZoomDrawer(
            moveMenuScreen: false,
            isRtl: true,
            controller: z,
            borderRadius: 24,
            style: DrawerStyle.style1,
            showShadow: true,
            openCurve: Curves.fastOutSlowIn,
            slideWidth: MediaQuery.of(context).size.width * .55,
            duration: const Duration(milliseconds: 500),
            angle: 0.0,
            mainScreen: _AuthorList(),
            menuScreen:_SliderView()
            //_SliderView(),
          )

**Comment by NikhilVadoliya** [comment]
Can you please share code and video? are you using `ZoomDrawer` plugin ?

**Comment by NikhilVadoliya** [comment]
Not longer comment on this issue and this is not an issue in this plugin so closed this issue.
