### ISSUE TITLE
[Feature Request] customize hamburger icon

### ISSUE THREAD

**Issue by wh120** [NikhilVadoliya/Flutter_slider_drawer#28]

**Comment by willyabraham** [comment]
please add the posibility of modify the icons

**Comment by NikhilVadoliya** [comment]
Hello @wh120  and @willyabraham, We have the "appBar" parameter in the widget. If you set it to null, then you can use your own app bar with a hamburger icon and control the animation. 

if you are still facing the issues, then reopen the ticket and share the video with the code
