### ISSUE TITLE
How to use without appbar

### ISSUE THREAD

**Issue by NaufalHafizi** [NikhilVadoliya/Flutter_slider_drawer#3]
Hi thank you for this package. how to apply without appbar ?
can i apply to specific button ?

**Comment by NikhilVadoliya** [comment]
You should be set below parameter if hiding appbar.

1. Not apply the `title` widget to `SliderMenuContainer` 
2. Set `appBarPadding` to 0
3. Set `appBarHeight` to 0


Yes, You can apply specific button and perform drawer action by 
```
 _key.currentState.closeDrawer();
 _key.currentState.openDrawer();
 _key.currentState.toggle();
 _key.currentState.isDrawerOpen();
```
