### ISSUE TITLE
Clicking Drawer Icon doesn't open when Custom Drawer Icon is Provided

### ISSUE THREAD

**Issue by devDonald** [NikhilVadoliya/Flutter_slider_drawer#33]
Scaffold(
      backgroundColor: Colors.white,

      body: SliderDrawer(
          slideDirection: slideDirection,
          animationDuration: 400,
          appBar: SliderAppBar(
            appBarHeight: 150,
            appBarPadding: const EdgeInsets.only(left: 30, top: 24),
            drawerIcon: SvgPicture.asset("assets/icons/menu_icon.svg"),
            drawerIconColor: ExchangeColors.blackColor,
            drawerIconSize: 50,
            appBarColor:ExchangeColors.whiteColor,
            title: Padding(
              padding: const EdgeInsets.only(top: 15.0),
              child: Text("", style:GoogleFonts.inter(fontSize: 22,fontWeight: FontWeight.bold,color: ExchangeColors.primaryColor),
              ),
            ),
            trailing: Padding(
              padding: const EdgeInsets.only(top: 15,right: 15),
              child: GestureDetector(
                onTap: (){
                  Get.to(()=> const MyProfileScreen());
                },
                child: const Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    //
                    // IconButton(onPressed: (){
                    //
                    // }, icon: const Icon(Icons.messenger_outlined,color: GlaColors.appBarIconsColor,)),
                    CircleAvatar(
                      radius: 30,
                      backgroundColor: Colors.white,
                      child: CircleAvatar(
                        radius: 25,
                        backgroundImage: CachedNetworkImageProvider(
                            'https://nikhilvadoliya.github.io/assets/images/nikhil_1.webp'),
                      ),
                    ),
                  ],),
              ),
            ),
          ),
          key: _sliderDrawerKey,
          sliderOpenSize: 260,

          slider: SliderView(
            onItemClick: (title) {
              _sliderDrawerKey.currentState!.closeSlider();
              setState(() {
                this.title = title;
              });
            },
          ),
          child:const HomeScreen() ),
    );

Anytime I provide a custom drawer icon when I click the icon the drawer doesn't open I have to to drag it and when it opens the drawer icon doesnt change to close icon and click it does'nt close the drawer. please any code snippet to solve this.

**Comment by NikhilVadoliya** [comment]
Hello @devDonald, If you use a custom drawer icon then you should use `GlobalKey` with `SliderDrawerState` and manage the drawer icon state and open and close the drawer.

Example : 

```
class _MyAppState extends State<MyApp> {
  GlobalKey<SliderDrawerState> _key = GlobalKey<SliderDrawerState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SliderDrawer(
      key: _key,
      appBar: SliderAppBar(
          appBarColor: Colors.white,
          title: Text('Title',
              style:
                  const TextStyle(fontSize: 22, fontWeight: FontWeight.w700))),
      slider: Container(color: Colors.red),
      child: Container(color: Colors.amber),
    ));
  }
}
      
```

For Open and Close

```
 _key.currentState.closeDrawer();
 _key.currentState.openDrawer();
 _key.currentState.toggle();
 _key.currentState.isDrawerOpen();
```

**Comment by devDonald** [comment]
Okay thank you
