### ISSUE TITLE
double container border color

### ISSUE THREAD

**Issue by carekb684** [NikhilVadoliya/Flutter_slider_drawer#5]
Hello, thanks for this plugin.

If you try to create a similar design to the one that is in the Readme (white appbar + white background in the body) but with a different color, say green. You will see a 1 pixel line between the appbar and body. This is because the appbar is a container, and the widget.sliderMain will likely also be a container.
This line can be removed by changing this at the end of the build() method:

Expanded( child:widget.sliderMain)

To:

Expanded(
                      child: Container(
                          decoration: BoxDecoration(
                            color: widget.appBarColor,
                            border: Border.all(width: 0, style: BorderStyle.none),
                          ),
                          child: widget.sliderMain)),

**Comment by NikhilVadoliya** [comment]
Hi @carekb684 , Thank you for finding this issue and suggestion.  You can solve this issue by below way with proper code


```
   /// Display Main Screen
      AnimatedContainer(
          duration:
              Duration(milliseconds: widget.sliderAnimationTimeInMilliseconds),
          curve: Curves.easeIn,
          width: double.infinity,
          height: double.infinity,
            color: widget.appBarColor,  <--Here Changes
          transform: getTranslationValues(widget.sliderOpen),
```

you should be set appBarColor in **AnimatedContainer**  and solve this issue.

I have pushed my changes. so you can also update the plugin.(first delete plugin from .pub-cache folder)
