### ISSUE TITLE
How to open Slide Bar with slide Left Gesture?

### ISSUE THREAD

**Issue by nicks258** [NikhilVadoliya/Flutter_slider_drawer#6]
I am just wonder how can i open left slide menu with left to right slide gesture as common in normal slide drawer?

**Comment by nikhil-concetto** [comment]
This feature is pending. I will implement it.

**Comment by NikhilVadoliya** [comment]
Meanwhile, You can wrap GestureDecetor in Parent of **SliderMenuContainer** Widget and open/close by  _key.currentState.closeDrawer()/ _key.currentState.openDrawer(); .
;

**Comment by NikhilVadoliya** [comment]
Hey @nicks258 , Swipe feature available in latest version `1.2.0`. Update package and use it.
